name: alethic-ism-processor-general
channels:
#  - file:///app/conda/env/local_channel
#  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
#  - python-dotenv
#  - psycopg2
#  - pyyaml
#  - pydantic
#  - pydantic-core
#  - openai
#  - tenacity
#  - alethic-ism-core
#  - alethic-ism-db
